name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud

        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=tech-challenge-group-23_application
            -Dsonar.organization=tech-challenge-group-23
          projectBaseDir: .
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build


      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name:  Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build images
        run: docker build -f ../../Dockerfile .


      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
